### ISSUE TITLE
How to generate the .mat file about training dataset and val dataset in CHW_OWM.py?

### ISSUE THREAD

**Issue by ShilangChen1011** [beijixiong3510/OWM#12]
You give the dataset download url with [HWDB1 in Baidu cloud disk](https://pan.baidu.com/s/1o84jIrg#list/path=%2F). But it only has the images, I want to get the mat files so that it can directly run on your code with CASIA_HWDB. Can you give me the downloading URL.

**Comment by beijixiong3510** [comment]
You can use the code under this path https://github.com/beijixiong3510/OWM/tree/master/CASIA_HWDB/CHW_ResNet18 
or generate extracted features in other formats according to your own needs.
