### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by yangzhaonan18** [beijixiong3510/OWM#15]
RuntimeError: CUDA out of memory.

Hello, may I ask what is the memory size of your GPU? 

I'm running the OWM code with 8G GPU  and want to fix this(RuntimeError: CUDA out of memory.).

How can I modify this program to ensure that the experimental results are consistent with yours?

thank you

**Comment by yangzhaonan18** [comment]
Multiple GPU work

**Comment by yangzhaonan18** [comment]
Multiple GPUs work

**Comment by frankdeepl** [comment]
> Multiple GPUs work

May I know how do you change the code?

**Comment by liangshuoying** [comment]
同样的问题，，求答复。

**Comment by beijixiong3510** [comment]
Please refer to https://github.com/beijixiong3510/OWM/issues/3#issuecomment-521946580
