### ISSUE TITLE
about the feature extractor

### ISSUE THREAD

**Issue by liujianzhao6328057** [beijixiong3510/OWM#16]
Thanks for your great work. I have some doubts about owm.
1.In the setting of jointly training the feature extractor and  the classifier, the architecture of the feature extractor is very simple.  If we replace the simple feature extractor with resnet18 or vgg, will OWM still work? 
2. Why the bias of the conv weight  is all set to zero? If we use resnet18 as the feature extractor, should we set bias of each conv to zero?

**Comment by beijixiong3510** [comment]
I think what feature extractor to use depends on your task. If it can be trained in an end to end way like the cifar task in our paper, the feature extractor is actually not the most important. 2 Usually the network will use bias, but it is not necessary, and the impact on network performance is not very significant.  You can add a dimension to weight to realize the calculation of bias.
Thank you for your attention to our work.
