### ISSUE TITLE
I can not get the same result

### ISSUE THREAD

**Issue by henuykc** [beijixiong3510/OWM#17]
I ran the OWM_ CNN code, but the running results is not similar with res.txt . After each task training, its test accuracy in other tasks is zero. The parameters are all default parameters. Is it that I did not run correctly?

**Comment by beijixiong3510** [comment]
Please refer to #3 (comment)

**Comment by henuykc** [comment]
I think you may have misunderstood me. There is no oom in my code. I mean, my run results are inconsistent with the run logs in the repository. Even if I set the epochs of the code to 1, the test accuracy of all tasks except the current task is 0. The code is pulled directly from this repository. I only modified epochs. Have you encountered this problem in the process of perfecting the code? How to solve it?
[log.txt](https://github.com/beijixiong3510/OWM/files/5606640/log.txt)

**Comment by beijixiong3510** [comment]
没有的，加微信beijixiong3510看看。



---Original---

**Comment by henuykc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    同学你好，你发的微信号用户不存在，是不是你的微信号换了。麻烦你加以下我的吧，Ykc757841004，感谢
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yaohanju
                            
                    
                        
                            
                                    yaohanju@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/27/2020 16:05，beijixiong3510<notifications@github.com> wrote： 




没有的，加微信beijixiong3510看看。















---Original---



From: "Henu_ykc"<notifications@github.com&gt;



Date: Fri, Nov 27, 2020 16:00 PM



To: "beijixiong3510/OWM"<OWM@noreply.github.com&gt;;



Cc: "State change"<state_change@noreply.github.com&gt;;"beijixiong3510"<975480992@qq.com&gt;;



Subject: Re: [beijixiong3510/OWM] I can not get the same result (#17)



















 



I think you may have misunderstood me. There is no oom in my code. I mean, my run results are inconsistent with the run logs in the repository. Even if I set the epochs of the code to 1, the test accuracy of all tasks except the current task is 0. The code is pulled directly from this repository. I only modified epochs. Have you encountered this problem in the process of perfecting the code? How to solve it?



 



—



You are receiving this because you modified the open/close state.



Reply to this email directly, view it on GitHub, or unsubscribe.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
