### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by leondada** [beijixiong3510/OWM#3]
The 'train_epoch' in OWM_CNN/owm.py always fills up the GPU's memory.
It seems that the memory space for each batch training has been accumulating.

**Comment by leondada** [comment]
Adding 'with torch.no_grad(): '  before 'for n, w in self.model.named_parameters():' can temporarily solve this problem.

**Comment by beijixiong3510** [comment]
Please pay attention to the **versions** of your  CUDA  or various python packages.AND the os.environ["CUDA_VISIBLE_DEVICES"] should rely on the index of your GPU in your PC.

**Comment by beijixiong3510** [comment]
The version of your torch is too high.

**Comment by AmanGoyal99** [comment]
Despite changing the cuda version, the code is not working. The GPU memory usage just keeps on increasing when I run the shuffled mnist programs. Any help would be appreciated.

**Comment by beijixiong3510** [comment]
You can refer to other related issues.



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 3, 2021 18:17 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [beijixiong3510/OWM] CUDA out of memory (#3)




 
Despite changing the cuda version, the code is not working. The GPU memory usage just keeps on increasing when I run the shuffled mnist programs. Any help would be appreciated.

**Comment by AmanGoyal99** [comment]
> You can refer to other related issues.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 3, 2021 18:17 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [beijixiong3510/OWM] CUDA out of memory (#3) Despite changing the cuda version, the code is not working. The GPU memory usage just keeps on increasing when I run the shuffled mnist programs. Any help would be appreciated. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

I did refer but none of them work. When I was running the shuffled MNIST and CIFAR programs, gpu memory was only increasing and it became full after initial 3 epochs and then the program stopped. Could it be due to the way data is being read in  the program? I am asking because there was no problem in running the Disjoint MNIST programs. Also, I have tried changing the torch versions to 0.4   but no program works.

**Comment by beijixiong3510** [comment]
Sorry, I wrote this code in 2018. Many packages are very old. Moreover, due to personal reasons, the code will no longer be maintained. You can modify it according to your own needs.
