### ISSUE TITLE
blog "Tensorflow and Chinese Handwritten Chinese Character Recognition" not found

### ISSUE THREAD

**Issue by ShilangChen1011** [beijixiong3510/OWM#7]
Hi,
The website "http://python.jobbole.com/87509/" is unreachable. So I can`t handle CASIA_HWDB dataset. Can you give me the solution.

**Comment by beijixiong3510** [comment]
I'm sorry for the original link is invalid,please refer to the other relative link https://www.jianshu.com/p/27efcf38c0c9
