### ISSUE TITLE
How to get the chwdata_mat files about training

### ISSUE THREAD

**Issue by ShilangChen1011** [beijixiong3510/OWM#8]
I have trained the datasets about CASIA_HWDB, but I can`t run the CHW_OWM.py. I found my "test_each  chwdata_mat" and "train_each  chwdata_mat" is wrong.
It seems the code about followed have the error.
```
ss = np.arange(train_length)
        np.random.shuffle(ss)
        trainimages = trainimages[ss, :]
        trainlabels = trainlabels[ss]
```
```
Traceback (most recent call last):
  File "/media/hdd/yike/OWM/CASIA_HWDB/CHW_OWM.py", line 60, in <module>
    trainlabels = trainlabels[ss]
IndexError: index 289 is out of bounds for axis 0 with size 1
```
So how I get the data?

**Comment by beijixiong3510** [comment]
This is related to the shape of your ‘ trainlabels’.You can change the code according to your needs.
