### ISSUE TITLE
About OWM_CNN, using Pytorch0.4 will out of memory, how to modify？

### ISSUE THREAD

**Issue by O1sInfo** [beijixiong3510/OWM#9]
The code of OWM_CNN can only use the pytorch0.3 version, and the 0.4 version and above will run out of memory. Would you like to ask if there is any code compatible with version 0.4 and above?

**Comment by beijixiong3510** [comment]
https://github.com/beijixiong3510/OWM/issues/3#issuecomment-521946580
However, this method cannot guarantee the reproduction of the result.
